### ISSUE TITLE
add strand specific bigwig tracks	

### ISSUE THREAD

**Issue by oliverdrechsel** [imbforge/NGSpipe2go#11]

**Comment by adomingues** [comment]
Right now I have two steps for this in the small RNA pipeline:
1. separate strands with [samtools](https://github.com/imbforge/NGSpipe2go/blob/master/modules/SmallRNAseq/split_read_strands.module.groovy) 
2. [bam2wig](https://github.com/imbforge/NGSpipe2go/blob/master/modules/SmallRNAseq/bam2bw.module.groovy)

I have been wanting to simplify this and implement [this](http://deeptools.readthedocs.io/en/latest/content/tools/bamCoverage.html#separate-tracks-for-each-strand) from DeepTools'. It would be a single step:

```
# Forward strand
bamCoverage -b a.bam -o a.fwd.bw --samFlagExclude 16

# Reverse strand
bamCoverage -b a.bam -o a.rev.bw --samFlagInclude 16
```

**Comment by karaulanov** [comment]
nice shortcut, just remember to normalize the tracks for comparability, I usually do RPM

**Comment by adomingues** [comment]
Good point and `bamCoverage` has options to normalized in several ways:
- RPKM
- normalizeTo1x (sequencing depth = (total number of mapped reads \* fragment length) / effective genome size), which I think it is similar to RPMs and I regularly use for other applications.
- and scale factor in combination with one of the above.
  See [this](http://deeptools.readthedocs.io/en/latest/content/tools/bamCoverage.html) and [this](https://groups.google.com/forum/#!searchin/deeptools/RPGC%7Csort:relevance/deeptools/th96gaftAXQ/jBuUVfFMyMMJ). 

It is something that I need to test at some point: generate tracks with both methods and check them out in IGV.

**Comment by nkreim** [comment]
Hi also used the original deeptools method and have it as a bpipe module already (for a specific project). It should be relatively straight forward to implement it. I will have a look next week.

**Comment by adomingues** [comment]
Added to the pipeline in commits: 06bff4912a11460d633b7bd3548263aac0c47ae4 and 7db0b4f5589738c65442cac425a119a94b1327bd. Currentely located in `modules/SmallRNAseq/bamCoverageStrands.module.groovy` because it uses my tool calling method. Please copy to `NGS` and add `source` as needed by the CFB.
