### ISSUE TITLE
implement chromosome overrepresentation

### ISSUE THREAD

**Issue by oliverdrechsel** [imbforge/NGSpipe2go#12]
- implement chromosome overrepresentation
- is chromosome coverage even?
- are differentially expressed / accumulated transcripts from genes in certain enriched regions in the genome?
- chi^2 or fisher test?
- maybe suitable R package: https://bioconductor.org/packages/release/bioc/html/Category.html (chapter 5)

**Comment by adomingues** [comment]
Also look into [GeneOverlap package](http://rpackages.ianhowson.com/bioc/GeneOverlap/man/GeneOverlap.html). Pretty straightforward to use. I did some similar tests in the past: [here](http://adomingues.github.io/2016/02/14/test-gene-overlap/) and [here](http://adomingues.github.io/2015/03/19/chromosome-over-representation-in-DGE/).

**Comment by adomingues** [comment]
Function written, but untested. Will do when there is a test data set available (DESeq2 results with genomic locations).

**Comment by adomingues** [comment]
Hopefully done in cdc4925037d292805c2bb2669bfa8eb5414893e2.
Thanks @nkreim for the bug fixes.
