### ISSUE TITLE
create plot of differentially expressed genes on chromosomes (perhaps with ideograms)?	

### ISSUE THREAD

**Issue by oliverdrechsel** [imbforge/NGSpipe2go#13]

**Comment by adomingues** [comment]
[ggbio](https://bioconductor.org/packages/release/bioc/html/ggbio.html)? It might not look great when there are too many overexpressed genes. Here is an example (not optimised): 
[hits_in_chromosome.pdf](https://github.com/imbforge/NGSpipe2go/files/513463/hits_in_chromosome.pdf)
Alternatively with [Gviz](https://bioconductor.org/packages/release/bioc/html/gviz.html), each chromosome has to plotted independently, but has ideograms (for certain species), and is better visually.

**Comment by ssayols** [comment]
yet another approach, getting the chromosome band information from UCSC and
plotting it with R and the grid package

**Comment by adomingues** [comment]
@ssayols it just occurred to me that not all species have band information - karyotype. I ran into that problem before. Something to keep in mind.

**Comment by ssayols** [comment]
iepp, sure... I guess the most common species we're working in-house will
have a "chromosome band" table in ucsc genome browser. Don't know how you
planned to test the overrepresentation; if in R/ or python, you can even
download the table on the fly (I think it's a mysql database that you can
connect with any client).

2016-10-17 17:21 GMT+02:00 A. Domingues notifications@github.com:

**Comment by StefanReuscher** [comment]
This might be a really old issue and should probably be closed. However, given recent communication with @karaulanov, I would like to mention my solution to plotting DEGs on chromosomes using ggplot2 only:

https://github.com/StefanReuscher/Deepwater-Rice-Timecourse
then: server.r from line 153

or deployed at: http://133.6.22.12/visualize-and-analyze-dwr-rnaseq-data
PW SNORKEL1, then chromosome overview tab

Gruß,

Stefan
