### ISSUE TITLE
env.sh requirement

### ISSUE THREAD

**Issue by AMChalkie** [imbforge/NGSpipe2go#34]
Hi,

Can you confirm what env.sh? I'm getting the following error which looks like a path issue, or do you expect a env.sh file to be added to each tool used in the pipeline?

Thanks
/Alistair

bash: line 1: /mnts/stemcell-bioinfo/src/FastQC/env.sh: No such file or directory
bash: line 1: /mnts/stemcell-bioinfo/src/STAR-2.5.2a/env.sh: No such file or directory
bash: line 1: /mnts/stemcell-bioinfo/src/STAR-2.5.2a/env.sh: No such file or directory
bash: line 1: /mnts/stemcell-bioinfo/src/FastQC/env.sh: No such file or directory
ERROR: stage FastQC failed: Command failed with exit status = 1 : 

export TOOL_DEPENDENCIES=/usr/bin && source /mnts/stemcell-bioinfo/src/FastQC/env.sh &&  			echo 'VERSION INFO'  1>&2 && 			echo $(fastqc --version | cut -d' ' -f2) 1>&2 && 			echo '/VERSION INFO' 1>&2 &&  			fastqc --extract --quiet -o /project/qc/fastqc rawdata/SRR2912019_paired_2.fastq.gz

**Comment by ssayols** [comment]
Hi Alistair,
the env.sh scripts contain the required environment, pretty much what you do with lmod modules. Basically, paths of the tools and their dependencies. That's how our Fastqc env.sh looks like:
```{bash}
$ cat env.sh 
export PATH=${TOOL_DEPENDENCIES}/fastqc/0.11.4:$PATH
source ${TOOL_DEPENDENCIES}/jdk/default/env.sh

$ cat ${TOOL_DEPENDENCIES}/jdk/default/env.sh
export PATH=${TOOL_DEPENDENCIES}/jdk/1.8.0_102/bin:$PATH
export JAVA_HOME=${TOOL_DEPENDENCIES}/jdk/1.8.0_102/
```
If you have all the tools already in your PATH, you can remove any references to env.sh from the modules. If you have a different environment system available, like lmod, they can be replaced with the coresponding call to "module load".

Hope this helps.

cheers,
Sergi
