### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by adomingues** [imbforge/NGSpipe2go#38]
Not very important, but it would be useful to have a sort of style-guide(lines) for the code. This guide will be particularly helpful for other developers, in-house or external, to read our code and to extend it. Right now we are more less doing the same, but there some differences in:

- naming of files
- number of tabs/spaces
- naming of bpipe stages

For example, I am naming my pipeline files as `some_pipe.pipeline.groovy`. This makes it clear that it is a pipeline file, and the extension `groovy` tells the code editor how to highlight the code. Which convention we use is not important as long as we are consistent. For the sake of code highlighting (sublime text) my stages start with capital letters (`Bowtie_se = { ` vs `bowtie_se = { `). 

If you think this is a good idea, I can start by writing some of the the things which are consistent as of now, and list those which are not. The "style-guide" would be located in `resources` at least until the docs are moved to a  project wiki or something.

**Comment by ssayols** [comment]
great! I think it's a very good idea, at some point I also started to get mad at tabs/spaces... I'll open a wiki page so we can all note down our thoughts there.

thanks!
S.

**Comment by adomingues** [comment]
>  I'll open a wiki page so we can all note down our thoughts there.

Perfect! I will wait for that then.

**Comment by ssayols** [comment]
[First iteration](https://github.com/imbforge/NGSpipe2go/wiki/Style_guide). Feel free to add and remove stuff. The coding style is somewhat buried in the **Modules** section, perhaps it deserves its own section.

Also in the main page of the wiki there're a couple of links to pages it'd be nice to fill out. And probably many more things could be added there. It's a wiki, so feel free to grow it as you like!
