### ISSUE TITLE
bowtie1pe and fastq.gz

### ISSUE THREAD

**Issue by adomingues** [imbforge/NGSpipe2go#41]
Currently using, and modifying the `CHiP-seq` pipeline and it crashes in `bowtie1pe`. The issue, as far as I can tell, is that `bowtie1` doesn't accept compressed `fastq` as input. Or am I missing something?

My current hacky solution was to include in the stage a de-compression step:

```bash
READ1=$output.dir/$OUTPUTFILE".R1.fastq"
READ2=$output.dir/$OUTPUTFILE".R2.fastq"

zcat $input1 > $READ1 &&
zcat $input2 > $READ2 &&
			
bowtie $BOWTIE_FLAGS $BOWTIE_REF -1 $READ1 -2 $READ2 | samtools view $SAMTOOLS_VIEW_FLAGS - | samtools sort $SAMTOOLS_SORT_FLAGS -T $TMPDIR/\$(basename $output.prefix) - > $output &&
``` 

Those files are then removed after mapping. There are all sort of problems with this solution, but it works for me for now. 

My suggestion: either remove the `bowtie1pe` stage or add in the description that it only works with uncompressed data.

**Comment by ssayols** [comment]
I'd suggest using redirection in bash (not sure about the exact syntax):

`bowtie $BOWTIE_FLAGS $BOWTIE_REF -1 <(zcat $input1) -2 <(zcat $input2)`

It's especially important to avoid creating unnecessary heavy loads of I/O in our NetApp, where each node has a 10GB connection only.

**Comment by adomingues** [comment]
It works. I completely forgot that was an option for newer bash versions.

Cheers.
