### ISSUE TITLE
MultiQC NGS module

### ISSUE THREAD

**Issue by ssayols** [imbforge/NGSpipe2go#48]

**Comment by ssayols** [comment]
Hi Peppe, I just saw this commit: 804147d8aff41dd9a6e2e1ca656e5b75c691c4cb. Can this issue be closed? Thanks!

**Comment by Joeblack83** [comment]
Hi Sergi, I think it can be closed. The module should work even though it has not been tested with the new structure of the pipeline included in the devel branch.

**Comment by ssayols** [comment]
Perfect! I'll test it along with other stuff
