### ISSUE TITLE
use \${TMP} to sort bam file

### ISSUE THREAD

**Issue by ssayols** [imbforge/NGSpipe2go#63]
Hey Frank,
I think here is a good place to use the scratch disks. Sorting generated hundreds of small temporary files that get eventually merged into the final sorted BAM file:

https://github.com/imbforge/NGSpipe2go/blob/8d78ecd3f01cdf04d4f4d783d054de4bf322a33b/modules/scRNAseq/subread.module.groovy#L48

**Comment by frankRuehle** [comment]
Hi Sergi, yes, I agree we should also use scratch disks there. I'll update the module accordingly.
